### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by bogas04**
* Nitnem Baani Progressbar
* ~~DisplayOnScroll AngBar in `/SGGS`~~ (Will take up in next sprint)
* Fix a typo in Jaap Sahib document.
* React to online/offline events to update NavBar color.
* Bump Cache Keys
* Update font styles of Baani
* Update Shabad Search Result Cards' Actions UI a bit.

### CODE REVIEW

**Comment by bogas04** [comment]
@shubhnik I would like you to review this PR. Thanks!

**Comment by bogas04** [comment]
Site can be previewed [here](https://gifted-engelbart-d7d624.netlify.com/).

**Comment by shubhnik** [comment]
@bogas04 the progress bar for Nitnem baanis is not visible in chrome, we need to work on this.

**Comment by shubhnik** [comment]
Great, progress bar now working smoothly for Nitnem baanis 👍

**Comment by bogas04** [comment]
Hi @shubhnik, could you please test the latest version once to see if all works fine? Thank you so much for taking out time for this! 

[preview-link](https://deploy-preview-124--gifted-engelbart-d7d624.netlify.com/#/)

Thanks a lot !

**Comment by shubhnik** [comment]
LGTM 👍 . Thanks for taking time from your busy schedule and working hard for this project. Great!!!

**Comment by bogas04** [comment]
@shubhnik thanks! Please approve the changes so that I can go ahead with merging to master.

**Review by shubhnik — APPROVED** [review]

**Pull request merged**
